repos:
- hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-json
  - id: check-merge-conflict
  - id: check-added-large-files
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: f1dff44d3a9ae852957f34def96390f28719c232
- hooks:
  - args:
    - --fix
    id: ruff
  - id: ruff-format
  repo: https://github.com/astral-sh/ruff-pre-commit
  rev: c53b915162b475dfc95c73f94219e6f87ace2fca
- hooks:
  - id: mypy
  repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.19.1
- hooks:
  - id: bandit
  repo: https://github.com/PyCQA/bandit
  rev: 4dacfcbe3651ae13a4dce10d6025086bfceed8be
- hooks:
  - id: detect-secrets
  repo: https://github.com/Yelp/detect-secrets
  rev: 50119d658ab48021cad234fc5c8d3253263b2ec0
- hooks:
  - id: debugger-detection
  - id: python-print-detection
  - id: python-logger-detection
  - id: env-file-check
  - id: yaml-sorter
  - id: json-sorter
  repo: https://github.com/chrysa/pre-commit-tools
  rev: b97ae91d8a45eb6f556fe938fa8bd58294c9a5e6
